module.exports = [
  {
    ProductImage: "https://i.ibb.co/gMzt0Qn/Mac-Book-Pro.jpg",
    ProductName: "iPhone 13",
    BrandName: "Apple",
    ProductType: "Phone",
    ProductPrice: "$999",
    ProductDescription: "The latest iPhone with advanced features.",
    ProductRating: "5",
  },
  {
    ProductImage: "https://i.ibb.co/19G9nbw/i-Phone-13.webp",
    ProductName: "MacBook Pro",
    BrandName: "Apple",
    ProductType: "Computer",
    ProductPrice: "$1,299",
    ProductDescription: "Powerful laptop for professionals.",
    ProductRating: "4.8",
  },
  {
    ProductImage: "https://i.ibb.co/DQvPMCv/Air-Pods-Pro.webp",
    ProductName: "AirPods Pro",
    BrandName: "Apple",
    ProductType: "Headphones",
    ProductPrice: "$249",
    ProductDescription: "Premium noise-canceling earbuds.",
    ProductRating: "4.9",
  },
  {
    ProductImage: "https://i.ibb.co/2MDDy44/iPad-Air.jpg",
    ProductName: "iPad Air",
    BrandName: "Apple",
    ProductType: "Tablet",
    ProductPrice: "$499",
    ProductDescription: "Lightweight and powerful iPad.",
    ProductRating: "4.7",
  },
  {
    ProductImage: "https://i.ibb.co/N3k22Zc/Apple-Watch-Series-7.webp",
    ProductName: "Apple Watch Series 7",
    BrandName: "Apple",
    ProductType: "Smartwatch",
    ProductPrice: "$399",
    ProductDescription: "Stay connected with the latest Apple Watch.",
    ProductRating: "4.6",
  },

  // Google Products
  {
    ProductImage: "https://i.ibb.co/rs6LLRK/pixel-6.jpg",
    ProductName: "Pixel 6",
    BrandName: "Google",
    ProductType: "Phone",
    ProductPrice: "$799",
    ProductDescription: "Google's flagship smartphone with an amazing camera.",
    ProductRating: "4.9",
  },
  {
    ProductImage: "https://i.ibb.co/HT6cBNy/Pixelbook.jpg",
    ProductName: "Pixelbook",
    BrandName: "Google",
    ProductType: "Laptop",
    ProductPrice: "$999",
    ProductDescription: "High-performance Chromebook by Google.",
    ProductRating: "4.7",
  },
  {
    ProductImage: "https://i.ibb.co/wyK2wGf/Nest-Audio.webp",
    ProductName: "Nest Audio",
    BrandName: "Google",
    ProductType: "Smart Speaker",
    ProductPrice: "$99",
    ProductDescription: "Smart speaker with impressive sound quality.",
    ProductRating: "4.5",
  },
  {
    ProductImage: "https://i.ibb.co/2SJcdPh/Chromecast-with-Google-TV.webp",
    ProductName: "Chromecast with Google TV",
    BrandName: "Google",
    ProductType: "Streaming Device",
    ProductPrice: "$49",
    ProductDescription: "Enjoy streaming with Google TV.",
    ProductRating: "4.8",
  },
  {
    ProductImage: "https://i.ibb.co/x1gHcN9/Google-Nest-Hub.webp",
    ProductName: "Google Nest Hub",
    BrandName: "Google",
    ProductType: "Smart Display",
    ProductPrice: "$89",
    ProductDescription: "Smart display with Google Assistant.",
    ProductRating: "4.6",
  },

  // Microsoft Products
  {
    ProductImage: "https://i.ibb.co/16fYMFL/Surface-Laptop-4.jpg",
    ProductName: "Surface Laptop 4",
    BrandName: "Microsoft",
    ProductType: "Laptop",
    ProductPrice: "$1,299",
    ProductDescription: "Sleek and powerful laptop by Microsoft.",
    ProductRating: "4.8",
  },
  {
    ProductImage: "https://i.ibb.co/5FWXkb6/Xbox-Series-X.png",
    ProductName: "Xbox Series X",
    BrandName: "Microsoft",
    ProductType: "Gaming Console",
    ProductPrice: "$499",
    ProductDescription: "Next-gen gaming console for immersive gaming.",
    ProductRating: "4.9",
  },
  {
    ProductImage: "https://i.ibb.co/rb1styz/Surface-Pro-7.jpg",
    ProductName: "Surface Pro 7",
    BrandName: "Microsoft",
    ProductType: "Tablet",
    ProductPrice: "$899",
    ProductDescription: "Versatile tablet with laptop-class performance.",
    ProductRating: "4.6",
  },
  {
    ProductImage: "https://i.ibb.co/N7xg5nJ/Microsoft-365.webp",
    ProductName: "Microsoft 365",
    BrandName: "Microsoft",
    ProductType: "Software",
    ProductPrice: "$69.99/year",
    ProductDescription: "Subscription for Microsoft Office and more.",
    ProductRating: "4.7",
  },
  {
    ProductImage: "https://i.ibb.co/wKSYG51/Microsoft-Ergonomic-Keyboard.jpg",
    ProductName: "Microsoft Ergonomic Keyboard",
    BrandName: "Microsoft",
    ProductType: "Keyboard",
    ProductPrice: "$59.99",
    ProductDescription: "Comfortable and ergonomic keyboard.",
    ProductRating: "4.5",
  },

  // Intel Products
  {
    ProductImage: "https://i.ibb.co/TcjNRHp/Core-i9-11900-K.webp",
    ProductName: "Core i9-11900K",
    BrandName: "Intel",
    ProductType: "Processor",
    ProductPrice: "$549",
    ProductDescription: "High-performance desktop processor.",
    ProductRating: "4.8",
  },
  {
    ProductImage: "https://i.ibb.co/W2T5VvV/Intel-SSD-660p.jpg",
    ProductName: "Intel SSD 660p",
    BrandName: "Intel",
    ProductType: "Solid State Drive",
    ProductPrice: "$129",
    ProductDescription: "Fast and reliable SSD for storage solutions.",
    ProductRating: "4.7",
  },
  {
    ProductImage: "https://i.ibb.co/hYD8KS5/Intel-Core-i5-11600-K.jpg",
    ProductName: "Intel Core i5-11600K",
    BrandName: "Intel",
    ProductType: "Processor",
    ProductPrice: "$279",
    ProductDescription: "Mid-range processor for gaming and multitasking.",
    ProductRating: "4.6",
  },
  {
    ProductImage: "https://i.ibb.co/cCNZBX6/Intel-NUC-11.jpg",
    ProductName: "Intel NUC 11",
    BrandName: "Intel",
    ProductType: "Mini PC",
    ProductPrice: "$799",
    ProductDescription: "Compact and powerful mini PC by Intel.",
    ProductRating: "4.9",
  },
  {
    ProductImage: "https://i.ibb.co/k8fhmWW/Intel-Core-i7-11700-K.jpg",
    ProductName: "Intel Core i7-11700K",
    BrandName: "Intel",
    ProductType: "Processor",
    ProductPrice: "$399",
    ProductDescription: "High-performance CPU for gaming and content creation.",
    ProductRating: "4.8",
  },

  // MI Products
  {
    ProductImage: "https://i.ibb.co/Vp1c6hM/Xiaomi-Mi-11.jpg",
    ProductName: "Xiaomi Mi 11",
    BrandName: "MI",
    ProductType: "Phone",
    ProductPrice: "$699",
    ProductDescription: "Flagship smartphone with a stunning display.",
    ProductRating: "4.7",
  },
  {
    ProductImage: "https://i.ibb.co/qxdPDqf/Xiaomi-Mi-Notebook-Pro.jpg",
    ProductName: "Xiaomi Mi Notebook Pro",
    BrandName: "MI",
    ProductType: "Laptop",
    ProductPrice: "$999",
    ProductDescription: "Powerful and slim laptop for productivity.",
    ProductRating: "4.6",
  },
  {
    ProductImage: "https://i.ibb.co/JrfpHNQ/Xiaomi-Mi-Band-6.png",
    ProductName: "Xiaomi Mi Band 6",
    BrandName: "MI",
    ProductType: "Fitness Tracker",
    ProductPrice: "$49",
    ProductDescription:
      "Feature-packed fitness tracker with a vibrant display.",
    ProductRating: "4.8",
  },
  {
    ProductImage: "https://i.ibb.co/KF5ZXpN/Xiaomi-Mi-Smart-TV-4-S.webp",
    ProductName: "Xiaomi Mi Smart TV 4S",
    BrandName: "MI",
    ProductType: "Smart TV",
    ProductPrice: "$499",
    ProductDescription: "Immersive smart TV experience with 4K resolution.",
    ProductRating: "4.7",
  },
  {
    ProductImage: "https://i.ibb.co/JRmt4xv/Xiaomi-Redmi-Note-10.png",
    ProductName: "Xiaomi Redmi Note 10",
    BrandName: "MI",
    ProductType: "Phone",
    ProductPrice: "$249",
    ProductDescription:
      "Budget-friendly smartphone with a high-refresh-rate display.",
    ProductRating: "4.5",
  },

  // Samsung Products
  {
    ProductImage: "https://i.ibb.co/RCsBZGP/Samsung-Galaxy-S21.webp",
    ProductName: "Samsung Galaxy S21",
    BrandName: "Samsung",
    ProductType: "Phone",
    ProductPrice: "$799",
    ProductDescription: "Premium smartphone with a versatile camera system.",
    ProductRating: "4.9",
  },
  {
    ProductImage: "https://i.ibb.co/JHkWfzw/Samsung-Galaxy-Tab-S7.jpg",
    ProductName: "Samsung Odyssey G9",
    BrandName: "Samsung",
    ProductType: "Gaming Monitor",
    ProductPrice: "$1,699",
    ProductDescription: "Curved gaming monitor with high refresh rate.",
    ProductRating: "4.8",
  },
  {
    ProductImage: "https://i.ibb.co/4V08ct9/Samsung-Q90-T-QLED-TV.jpg",
    ProductName: "Samsung Galaxy Tab S7+",
    BrandName: "Samsung",
    ProductType: "Tablet",
    ProductPrice: "$849",
    ProductDescription: "Powerful Android tablet for productivity.",
    ProductRating: "4.7",
  },
  {
    ProductImage: "https://i.ibb.co/jMkhq7K/Samsung-Galaxy-Watch-4.jpg",
    ProductName: "Samsung Q90T QLED TV",
    BrandName: "Samsung",
    ProductType: "Smart TV",
    ProductPrice: "$1,499",
    ProductDescription: "QLED smart TV with impressive picture quality.",
    ProductRating: "4.8",
  },
  {
    ProductImage: "https://i.ibb.co/phQBFDp/Samsung-Odyssey-G9.jpg",
    ProductName: "Samsung Galaxy Watch 4",
    BrandName: "Samsung",
    ProductType: "Smartwatch",
    ProductPrice: "$249",
    ProductDescription:
      "Feature-rich smartwatch for fitness and health tracking.",
    ProductRating: "4.6",
  },
];
